## Фреймворк PyTorch для разработки искусственных нейронных сетей.

### Урок 1. Основные понятия и структуры PyTorch.

**1. Coздайте случайный FloatTensor размера 3x4x5.**

In [76]:
import numpy as np

import torch
from torch.autograd import Variable
from torch import nn 
from torch import optim

In [77]:
a = torch.arange(60).view(3, 4, 5)

a = a.to(torch.float)

print(a, '\n', a.type())

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]],

        [[20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34.],
         [35., 36., 37., 38., 39.]],

        [[40., 41., 42., 43., 44.],
         [45., 46., 47., 48., 49.],
         [50., 51., 52., 53., 54.],
         [55., 56., 57., 58., 59.]]]) 
 torch.FloatTensor


**2. Выведите его форму (shape).**

In [78]:
print(f'Тензор "a" имеет размерность- {a.shape}')

Тензор "a" имеет размерность- torch.Size([3, 4, 5])


**3. Приведите его к форме 6 X 10.**

In [79]:
a.reshape(6, 10)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
        [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.]])

**4. Умножьте его на вектор [1,  4,  2,  2,  1] поэлементно.**

In [80]:
b = torch.FloatTensor([1, 4, 2, 2, 1])

In [81]:
c = torch.mul(a, b)

c

tensor([[[  0.,   4.,   4.,   6.,   4.],
         [  5.,  24.,  14.,  16.,   9.],
         [ 10.,  44.,  24.,  26.,  14.],
         [ 15.,  64.,  34.,  36.,  19.]],

        [[ 20.,  84.,  44.,  46.,  24.],
         [ 25., 104.,  54.,  56.,  29.],
         [ 30., 124.,  64.,  66.,  34.],
         [ 35., 144.,  74.,  76.,  39.]],

        [[ 40., 164.,  84.,  86.,  44.],
         [ 45., 184.,  94.,  96.,  49.],
         [ 50., 204., 104., 106.,  54.],
         [ 55., 224., 114., 116.,  59.]]])

**5. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6.**

In [82]:
a = a.reshape(6, 10)

d = torch.matmul(a, a.T)

In [83]:
d

tensor([[  285.,   735.,  1185.,  1635.,  2085.,  2535.],
        [  735.,  2185.,  3635.,  5085.,  6535.,  7985.],
        [ 1185.,  3635.,  6085.,  8535., 10985., 13435.],
        [ 1635.,  5085.,  8535., 11985., 15435., 18885.],
        [ 2085.,  6535., 10985., 15435., 19885., 24335.],
        [ 2535.,  7985., 13435., 18885., 24335., 29785.]])

**6. Посчитайте производную функции y = x^3 + z - 75t в точке (1, 0.5, 2).**

In [84]:
x = Variable(torch.FloatTensor([1]),   requires_grad = True)

z = Variable(torch.FloatTensor([0.5]), requires_grad = True)

t = Variable(torch.FloatTensor([2]),   requires_grad = True)

y = x**3 + z -75*t

y.backward([x, z, t])

(x.grad, z.grad, t.grad)

(tensor([3.]), tensor([1.]), tensor([-75.]))

**7. Создайте единичный тензор размера 5x6.**

In [85]:
e = torch.ones(5, 6)

print(f'Единичный тензор размерности 5*6:\n{e}')

Единичный тензор размерности 5*6:
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


**8. Переведите его в формат numpy.**

In [86]:
e.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

**9. Давайте теперь пооптимизируем: возьмите функцию y = x^w1 - 2 * x^2 + 5. Посчитайте.**

In [87]:
w1 = Variable(torch.Tensor([0.1,0.1]), requires_grad = True)

x = Variable(torch.Tensor([2,2]), requires_grad = False)

y = Variable(torch.Tensor([2,2]), requires_grad = False)

In [88]:
optimizer = torch.optim.SGD([w1], lr=0.001)

criterion = torch.nn.MSELoss()

In [89]:
f = x**w1 - 2 * x**2 + 5

optimizer.zero_grad()
pred = f
loss = criterion(pred, y)

loss.backward()     
optimizer.step()   

In [91]:
print(f'loss:\t {loss.item()}\n')

print(f'w1:\t {w1.data}')

loss:	 15.430963516235352

w1:	 tensor([0.1029, 0.1029])
